baseURL = 'https://www.lucasciacca.com/'
languageCode = 'it-IT'
title = 'Luca Sciacca - Developer e Devops Engineer'

[params]
title = "Luca Sciacca"

# TODO localizza delle keyword e basa una strategia dopo la creazione di alcuni contenuti
description = "Ciao, sono Luca Sciacca, CTO in SEO Tester Online e questo è il mio sito web"
color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 2

#[[menu.main]]
#identifier = "projects"
#name = "Progetti"
#url = "/projects/"
#weight = 3

[[menu.main]]
identifier = "changelog"
name = "Changelog"
url = "/changelog/"
weight = 4

[[menu.main]]
identifier = "contacts"
name = "Contatti"
url = "/contact/"
weight = 5

# Footer Menu
[[menu.footer]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 2

[[menu.footer]]
identifier = "projects"
name = "Progetti"
url = "/projects/"
weight = 3

[[menu.footer]]
identifier = "changelog"
name = "Changelog"
url = "/changelog/"
weight = 4

[[menu.footer]]
identifier = "contact"
name = "Contatti"
url = "/contact/"
weight = 5

#-------------------------------
# Author Settings
[params.author]
author__name = "Luca Sciacca"
author__bio = "La mia passione è sperimentare e imparare continuamente nuove tecnologie, espandendo le mie conoscenze in diversi ambiti. Quando sviluppo un progetto cerco sempre di bilanciare funzionalità innovative con un'esperienza utente intuitiva, dando vita a creazioni che uniscono tecnologia e creatività."
author__avatar = "/images/me.webp"

# Social Links
[[params.social]]
icon = "ion-logo-facebook"
name = "Facebook"
link = "https://www.facebook.com/lucasciacca93/"

[[params.social]]
icon = "ion-logo-instagram"
name = "Instagram"
link = "https://www.instagram.com/lucasciaccadev/"

[[params.social]]
icon = "ion-logo-github"
name = "Github"
link = "https://github.com/Silverkron"

# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
[params.hero]
enable = true
hero__title = "Sono Luca e qui esploro e condivido le mie <span class=\"highlight\">passioni</span> ed <span class=\"highlight\">esperienze</span>"
hero__description = "Come sviluppatore e tech enthusiast, mi muovo tra sviluppo web, software, intelligenza artificiale, stampa 3D e IoT. Qui raccolgo i miei progetti, esperimenti e scoperte: un viaggio personale attraverso le tecnologie che mi appassionano. Entra nel mio laboratorio digitale e scopri come trasformo idee in realtà concrete."
hero__image = "/images/me.webp"


#-------------------------------
# Newsletter Settings
[params.mailchimp]
enable = false
mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text = "Your email address..."
mailchimp__button__text = "Get updates" # Add your button text


#-------------------------------
# Projects Settings
[params.projects]
enable = true
projects__title= "Ultimi progetti"
projects__description= "Una raccolta dei progetti sviluppati, evidenziando innovazione e competenza tecnica per fornire soluzioni efficaci e orientate ai risultati concreti."
projects__seeall = "Vedi tutto"

#-------------------------------
# Testimonials Section
[params.testimonials]
enable = false
testimonial__title = "Cosa dicono di me"
testimonial__description = ""
testimonial__linkedin_button_text = "Leggi altri feedback su Linkedin"
testimonial__linkedin_button_link = ""

[[params.testimonial_item]]
name = "Aspen Carder"
image = "https://via.placeholder.com/200x200"
designation = "Lettering Artist"
link = "https://twitter.com/"
content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

[[params.testimonial_item]]
name = "Lydia Siphron"
image = "https://via.placeholder.com/200x200"
designation = "Designer"
link = "https://facebook.com/"
content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

[[params.testimonial_item]]
name = "Craig Vaccaro"
image = "https://via.placeholder.com/200x200"
designation = "Web developer"
link = "https://twitter.com/"
content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

[[params.testimonial_item]]
name = "Anika Calzoni"
image = "https://via.placeholder.com/200x200"
designation = "Lettering Artist"
link = "https://facebook.com/"
content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

[[params.testimonial_item]]
name = "Marcus Botosh"
image = "https://via.placeholder.com/200x200"
designation = "Full Stack Designer"
link = "https://twitter.com/"
content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
[params.blog]
enable = true
blog__title = "Articoli recenti"
blog__description = "Esplora i miei ultimi articoli. Ogni pezzo offre approfondimenti pratici e strategie avanzate per supportare i professionisti del settore nell’aggiornamento e nel miglioramento continuo."
blog__seeall = "Vedi tutto"

#-------------------------------
# Gallery Footer Settings
[params.gallery]
enable = false

[[params.gallery_image]]
image_alt = "Rest"
image_url = "https://via.placeholder.com/800x800"

[[params.gallery_image]]
image_alt = "Lifestyle"
image_url = "https://via.placeholder.com/800x800"

[[params.gallery_image]]
image_alt = "Hobby"
image_url = "https://via.placeholder.com/800x800"

[[params.gallery_image]]
image_alt = "Notes"
image_url = "https://via.placeholder.com/800x800"


#-------------------------------
# Contact Settings
[params.contact]
contact__email = "hello@lucasciacca.com" # Add your form_id

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
[params.disqus]
enable = false
disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
